import React, {useEffect, useMemo, useState} from 'react';
import {Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, ComposedChart, Legend, Line, Pie, PieChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis} from 'recharts';
import {ArrowUpRight, BookOpen, ChartColumnIncreasing, Clock3, Database, Download, FlaskConical, Layers3, Menu, Search, Users, X} from 'lucide-react';
const BLUE='#2563eb',TEAL='#0b9488',COLORS=['#2563eb','#14a399','#6e79d6','#f2ac52','#91b9d4'];
const fmt=n=>Number(n??0).toLocaleString('zh-CN',{maximumFractionDigits:1});
const years=d=>d==null?'—':(d/365.25).toFixed(2);
const pct=n=>n==null?'—':`${n>0?'+':''}${n.toFixed(1)}%`;
const name=s=>s.replace(/^\([^)]*\)\s*/,'');
const short=(s,max=31)=>s.length>max?s.slice(0,max-1)+'…':s;
const NAV=[['overview','统计概览',ChartColumnIncreasing],['disciplines','学科与时滞',Layers3],['people','机构与作者',Users],['sources','数据与方法',BookOpen],['samples','样本观察',FlaskConical]];
function useJSON(path){const [state,setState]=useState({data:null,error:null});useEffect(()=>{const controller=new AbortController();fetch(path,{signal:controller.signal}).then(r=>{if(!r.ok)throw Error(`无法读取统计数据（${r.status}）`);return r.json()}).then(data=>setState({data,error:null})).catch(e=>{if(e.name!=='AbortError')setState({data:null,error:e.message})});return()=>controller.abort()},[path]);return state}
function Export({filename,rows}){function save(){if(!rows.length)return;const keys=Object.keys(rows[0]);const quote=v=>'"'+String(v??'').replace(/^[=+@\-\t\r]/,"'$&").replaceAll('"','""')+'"';const blob=new Blob(['\ufeff'+[keys,...rows.map(r=>keys.map(k=>r[k]))].map(row=>row.map(quote).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}return <button className="export" onClick={save} disabled={!rows.length}><Download size={15}/>统计 CSV</button>}
function ChartTip({active,payload,label}){if(!active||!payload?.length)return null;return <div className="tooltip"><b>{payload[0]?.payload?.name||label}</b>{payload.filter(p=>p.value!=null).map((p,i)=><div key={i}><i style={{background:p.color}}/>{p.name}：{Array.isArray(p.value)?p.value.map(fmt).join('–'):fmt(p.value)}</div>)}</div>}
function Panel({number,title,subtitle,children,action,className=''}){return <section className={`panel ${className}`}><div className="panel-head"><div><span className="section-number">{number}</span><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>{children}</section>}
function Note({observation,interpretation}){return <div className="analysis"><div><span>数据观察</span><p>{observation}</p></div>{interpretation&&<div><span>解释边界</span><p>{interpretation}</p></div>}</div>}
function Toggle({value,set,options}){return <div className="toggle">{options.map(([k,n])=><button key={k} aria-pressed={k===value} className={k===value?'active':''} onClick={()=>set(k)}>{n}</button>)}</div>}
function ChartTable({rows,headers}){return <details className="accessible-table"><summary>查看图表数据表</summary><div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h[0]}>{h[1]}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{headers.map(([k])=><td key={k}>{r[k]==null?'—':r[k]}</td>)}</tr>)}</tbody></table></div></details>}
function HorizontalBars({data,color=BLUE,valueLabel='论文关联数',height=330}){const rows=data.map(x=>({...x,name:x.name||x.label}));return <><div className="chart" style={{height}}><ResponsiveContainer width="100%" height="100%"><BarChart data={rows} layout="vertical" margin={{left:5,right:25,top:8,bottom:5}}><CartesianGrid strokeDasharray="3 5" horizontal={false} stroke="#e7edf3"/><XAxis type="number" tick={{fontSize:12}} tickFormatter={fmt} axisLine={false} tickLine={false}/><YAxis type="category" dataKey="name" width={155} tickFormatter={s=>short(name(s),23)} tick={{fontSize:12}} axisLine={false} tickLine={false}/><Tooltip content={<ChartTip/>}/><Bar dataKey="count" name={valueLabel} fill={color} radius={[0,4,4,0]} maxBarSize={22} isAnimationActive={false}/></BarChart></ResponsiveContainer></div><ChartTable rows={rows.map(r=>({name:r.name,count:fmt(r.count)}))} headers={[["name","分组"],["count",valueLabel]]}/></>}
function Overview({d}){const [clock,setClock]=useState('retracted'),[start,setStart]=useState(2000);const current=d.meta.partial_year;
 const data=useMemo(()=>d.trend[clock].map((v,i,all)=>({...v,mean:!v.partial&&i>=2?(all[i-2].count+all[i-1].count+v.count)/3:null})).filter(v=>v.year>=start),[d,clock,start]);
 const selected=data.reduce((s,v)=>s+v.count,0),lag=d.summary.lag;
 const completed=data.filter(v=>!v.partial);const peak=completed.length?completed.reduce((a,b)=>b.count>a.count?b:a):null;
 return <><div className="metrics">{[['撤稿原论文',fmt(d.summary.paper_count),'RW 快照 · 原论文键去重'],['日期有效的时滞样本',fmt(lag.n),'日期缺失或负时滞不参与'],['发表到撤稿 · 中位数',years(lag.median_days),'年 · 已撤稿样本'],['学科分类',`${d.taxonomies.rw.domains.length} / ${d.taxonomies.rw.disciplines.length}`,'一级领域 / 二级 Subject 标签']].map(([label,value,hint])=><div className="metric" key={label}><span>{label}</span><strong>{value}</strong><small>{hint}</small></div>)}</div>
 <p className="cohort-note">统计总体为 RW 快照中 Retraction 类别的去重原论文；并非全球撤稿总量。所有统计图表仅使用 RW 数据。</p>
 <Panel number="01" title="撤稿随时间如何变化？" subtitle="撤稿发生年与原论文发表年是两种不同的观察口径。" action={<Export filename="annual-statistics.csv" rows={data.map(v=>({year:v.year,count:v.count,date_basis:clock,partial_year:v.partial}))}/>}>
 <div className="chart-controls"><Toggle value={clock} set={setClock} options={[["retracted","实际撤稿年份"],["published","原论文发表年份"]]}/><label>展示范围<select value={start} onChange={e=>setStart(+e.target.value)}><option value={2000}>2000 年至今</option><option value={2015}>2015 年至今</option><option value={0}>全部年份</option></select></label><span>{fmt(selected)} 篇 · 图表范围内</span></div>
 <div className="chart big"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data} margin={{top:24,left:5,right:18,bottom:4}}><CartesianGrid vertical={false} strokeDasharray="3 5" stroke="#e4eaf1"/><XAxis dataKey="year" tick={{fontSize:12}} minTickGap={25} axisLine={false} tickLine={false}/><YAxis tickFormatter={fmt} tick={{fontSize:12}} axisLine={false} tickLine={false}/><Tooltip content={<ChartTip/>}/><Bar name="原论文数" dataKey="count" fill={BLUE} radius={[3,3,0,0]} isAnimationActive={false}>{data.map(v=><Cell key={v.year} fill={v.partial?'#99bacb':BLUE}/>)}</Bar><Line name="后向 3 年均值" dataKey="mean" stroke={TEAL} strokeWidth={2} dot={false} connectNulls={false} isAnimationActive={false}/><Legend iconType="circle" wrapperStyle={{fontSize:13,paddingTop:14}}/></ComposedChart></ResponsiveContainer></div>
 <Note observation={peak?`${clock==='retracted'?'撤稿发生':'原论文发表'}口径下，当前展示范围的完整年度峰值是 ${peak.year} 年（${fmt(peak.count)} 篇）。${current} 年为未完整年度。`:'当前范围没有完整年度数据。'} interpretation={clock==='retracted'?'年度变化反映记录中的撤稿处理数量，可能受到集中调查、批量处理与数据回补影响，不能据此断言学术不端发生率变化。':'这里统计的是某年发表、后来进入本撤稿队列的论文。较新发表年份观察期较短，不能直接与早期年份比较撤稿风险。'}/>
 <ChartTable rows={data.map(v=>({year:v.year,count:v.count,mean:v.mean==null?'—':fmt(v.mean)}))} headers={[["year","年份"],["count","原论文数"],["mean","后向 3 年均值"]]}/></Panel>
 <div className="two-col"><Panel number="02" title="从发表到撤稿，需要多久？" subtitle="按有效时间差分组；不包含尚未撤稿论文。"><div className="donut-layout"><div className="chart donut"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={lag.histogram} dataKey="count" nameKey="label" innerRadius="55%" outerRadius="83%" paddingAngle={2} isAnimationActive={false}>{lag.histogram.map((x,i)=><Cell key={x.label} fill={COLORS[i]}/>)}</Pie><Tooltip formatter={v=>[fmt(v)+' 篇','数量']}/></PieChart></ResponsiveContainer></div><div className="legend-list">{lag.histogram.map((x,i)=><div key={x.label}><i style={{background:COLORS[i]}}/><span>{x.label}</span><b>{lag.n?(x.count/lag.n*100).toFixed(1):'0'}%</b></div>)}</div></div><Note observation={`中间 50% 的有效样本落在 ${years(lag.p25_days)}–${years(lag.p75_days)} 年。`} interpretation="这是条件于已经撤稿的时滞分布，不能用来估计普通论文未来被撤稿的概率。"/><ChartTable rows={lag.histogram} headers={[["label","时间差"],["count","样本数"]]}/></Panel>
 <Panel number="03" title="一级学科分布" subtitle="RW 官方领域前缀 · 同一领域内按论文去重"><HorizontalBars data={d.taxonomies.rw.domains} height={280}/><p className="caption">同一篇论文可能属于多个学科，分组合计不能当作论文总数。数量未按各学科发文规模标准化。</p></Panel></div>
 <Panel number="04" title="可以从数据中读出什么？" subtitle="分析由当前统计快照生成，保留数值依据。"><div className="insight-grid">{d.insights.map((x,i)=><article key={x.title}><span className="insight-number">0{i+1}</span><h3>{x.title}</h3><p>{x.text}</p><p className="muted">{x.interpretation}</p></article>)}</div></Panel></>}
function Disciplines({d}){const [level,setLevel]=useState('1'),[parent,setParent]=useState(''),[selected,setSelected]=useState(''),[mode,setMode]=useState('full');const group=d.taxonomies.rw,fields=level==='1'?group.domains:group.disciplines.filter(f=>!parent||f.parent_id===parent);
 const field=fields.find(f=>f.id===selected)||fields[0];const top=[...fields].sort((a,b)=>mode==='full'?b.count-a.count:b.fractional_count-a.fractional_count).slice(0,12);
 const last=d.meta.partial_year-1;const heatYears=Array.from({length:10},(_,i)=>last-9+i);const heat=fields.slice(0,10);const max=Math.max(1,...heat.flatMap(f=>f.trend.retracted.filter(x=>heatYears.includes(x.year)).map(x=>x.count)));
 const changes=fields.filter(f=>!f.growth.small_base&&f.growth.percent!=null).sort((a,b)=>b.growth.percent-a.growth.percent).slice(0,12);
 const dispersion=fields.filter(f=>f.lag.n>=20).slice(0,8).map(f=>({name:f.name,p25:f.lag.p25_days/365.25,median:f.lag.median_days/365.25,p75:f.lag.p75_days/365.25}));
 return <><div className="scope-bar"><Toggle value={level} set={v=>{setLevel(v);setSelected('')}} options={[["1","一级学科"],["2","二级学科"]]}/>{level==='2'&&<label>所属一级学科<select value={parent} onChange={e=>{setParent(e.target.value);setSelected('')}}><option value="">全部领域</option>{group.domains.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label>}<span>当前 {fields.length} 个学科 · RW 全部 {fmt(group.scope_papers)} 篇队列</span></div>
 <div className="domain-grid">{group.domains.map(f=><button key={f.id} className={level==='2'&&parent===f.id?'active':''} onClick={()=>{setLevel('2');setParent(f.id);setSelected('')}}><span>{f.name} <small>{f.id}</small></span><strong>{fmt(f.count)}</strong><small>{group.disciplines.filter(x=>x.parent_id===f.id).length} 个二级学科 · 查看图表 ↗</small></button>)}</div><p className="caption">一级采用 RW 官方领域前缀，二级保留完整 Subject 标签；点击领域卡片查看其下属学科。一级按论文去重，不累加二级数量。<a href={group.hierarchy_source} target="_blank" rel="noreferrer">分类来源 ↗</a></p>

 <div className="two-col"><Panel number="01" title="学科关联数量" subtitle="当前层级与领域 · 关联数量前 12 项" action={<Toggle value={mode} set={setMode} options={[["full","全计数"],["fractional","分数计数"]]}/>}><HorizontalBars data={top.map(f=>({...f,count:mode==='full'?f.count:f.fractional_count}))} height={420}/><Note observation={top.length?`${name(top[0].name)} 在当前计数口径下居首，关联数为 ${fmt(mode==='full'?top[0].count:top[0].fractional_count)}。`:'暂无学科数据。'} interpretation="分数计数在当前层级将每篇论文平均分给全部不同学科；筛选一级领域后不重新分配权重。它未校正各学科发文规模。"/></Panel>
 <Panel number="02" title="学科撤稿数量同比" subtitle={`${last-1} → ${last} · 仅比较基期不少于 20 篇的学科 · 按同比排序前 12`}><div className="chart" style={{height:420}}><ResponsiveContainer width="100%" height="100%"><BarChart layout="vertical" data={changes.map(f=>({name:f.name,change:f.growth.percent}))} margin={{left:5,right:30}}><CartesianGrid horizontal={false} strokeDasharray="3 5"/><XAxis type="number" tickFormatter={v=>v+'%'} tick={{fontSize:12}}/><YAxis type="category" dataKey="name" width={145} tickFormatter={s=>short(name(s),21)} tick={{fontSize:12}} axisLine={false} tickLine={false}/><Tooltip formatter={v=>[pct(v),'数量同比']} labelFormatter={(_,p)=>p?.[0]?.payload.name}/><ReferenceLine x={0} stroke="#91a0b3"/><Bar dataKey="change" maxBarSize={20} isAnimationActive={false}>{changes.map(f=><Cell key={f.id} fill={f.growth.percent>=0?BLUE:TEAL}/>)}</Bar></BarChart></ResponsiveContainer></div><Note observation={changes.length?`在满足基期门槛的学科中，${name(changes[0].name)} 的数量同比最高（${pct(changes[0].growth.percent)}）。`:'没有满足基期门槛的可比较学科。'} interpretation="数量增长不是撤稿率上升。这里固定使用全计数；基期为零不计算百分比，低于 20 篇不进入排序。"/><ChartTable rows={changes.map(f=>({name:f.name,base:f.growth.base,latest:f.growth.latest,percent:pct(f.growth.percent)}))} headers={[["name","学科"],["base",String(last-1)],["latest",String(last)],["percent","同比"]]}/></Panel></div>
 <Panel number="03" title="学科 × 撤稿年份" subtitle="完整年度 · 关联数量前 10 学科 · 全计数"><div className="heat-wrap"><table className="heatmap"><thead><tr><th>学科</th>{heatYears.map(y=><th key={y}>{y}</th>)}</tr></thead><tbody>{heat.map(f=><tr key={f.id}><th title={f.name}>{name(f.name)}</th>{heatYears.map(y=>{const n=f.trend.retracted.find(v=>v.year===y)?.count||0;const intensity=n/max;return <td key={y} style={{background:`rgba(37,99,235,${.035+intensity*.9})`,color:intensity>.5?'white':'#243751'}} title={`${f.name} · ${y} 年：${n} 篇`}>{fmt(n)}</td>})}</tr>)}</tbody></table></div><p className="caption">每个单元格直接展示统计数值。跨学科可能重复计入同一论文，颜色深浅不代表不端发生风险。</p></Panel>
 <Panel number="04" title="不同学科的撤稿时滞" subtitle="按关联数量选择前 8 个有效日期样本 ≥20 的学科；展示 P25、中位数与 P75。"><div className="chart" style={{height:440}}><ResponsiveContainer width="100%" height="100%"><BarChart layout="vertical" data={dispersion} margin={{right:25,left:5}}><CartesianGrid horizontal={false} strokeDasharray="3 5"/><XAxis type="number" tickFormatter={v=>v+' 年'} tick={{fontSize:12}}/><YAxis type="category" dataKey="name" width={170} tickFormatter={s=>short(name(s),25)} tick={{fontSize:12}} axisLine={false} tickLine={false}/><Tooltip formatter={v=>[Number(v).toFixed(2)+' 年']} labelFormatter={(_,p)=>p?.[0]?.payload.name}/><Legend/><Bar dataKey="p25" name="P25" fill="#a5c7f5" isAnimationActive={false}/><Bar dataKey="median" name="中位数" fill={BLUE} isAnimationActive={false}/><Bar dataKey="p75" name="P75" fill={TEAL} isAnimationActive={false}/></BarChart></ResponsiveContainer></div><Note observation="三个分位数分别描述较短时滞、典型时滞和较长时滞；P75 与 P25 的距离表示中间一半样本的离散程度。" interpretation="学科之间的差异也可能来自论文发表年代、调查方式和数据收录差异，不能单独解释为某学科处理问题更快或更慢。"/><ChartTable rows={dispersion.map(f=>({name:f.name,p25:f.p25.toFixed(2),median:f.median.toFixed(2),p75:f.p75.toFixed(2)}))} headers={[["name","学科"],["p25","P25 / 年"],["median","中位数 / 年"],["p75","P75 / 年"]]}/></Panel>
 <Panel number="05" title="观察一个学科" subtitle="选定学科的全部已统计年度与时滞分布。" action={<label>学科<select value={field?.id||''} onChange={e=>setSelected(e.target.value)}>{fields.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label>}>{field?<><div className="inline-facts"><span>原论文 <b>{fmt(field.count)}</b></span><span>时滞样本 <b>{fmt(field.lag.n)}</b></span><span>中位时滞 <b>{years(field.lag.median_days)} 年</b></span></div><div className="two-col no-gap-bottom"><div className="chart" style={{height:260}}><ResponsiveContainer width="100%" height="100%"><AreaChart data={field.trend.retracted.filter(v=>v.year>=2000)} margin={{right:15,left:0}}><CartesianGrid vertical={false} strokeDasharray="3 5"/><XAxis dataKey="year" minTickGap={30} tick={{fontSize:12}}/><YAxis tick={{fontSize:12}}/><Tooltip content={<ChartTip/>}/><Area dataKey="count" name="实际撤稿数量" fill="#dbeafe" stroke={BLUE} type="linear" isAnimationActive={false}/></AreaChart></ResponsiveContainer></div><HorizontalBars data={field.lag.histogram} color={TEAL} height={240}/></div><p className="caption">最后一年为未完整年度，不能直接与前一年比较全年数量。</p></>:<p className="empty">当前没有学科匹配数据。</p>}</Panel></>}
function People({d}){const taxonomy='rw';const [mode,setMode]=useState('full');const group=d.taxonomies.rw;return <><div className="scope-bar"><span>Retraction Watch 原始署名 · 全队列</span><Toggle value={mode} set={setMode} options={[["full","全计数"],["fractional","分数计数"]]}/></div><div className="notice">这些是原始名称的关联分布。院系、地址和拼写变体可能拆分；同名作者也可能被合并。 关联数量不等于责任认定。</div>{[['institutions','机构关联分布',BLUE],['authors','作者关联分布',TEAL]].map(([key,title,color],i)=>{const stat=group[key],rows=stat[mode].slice(0,15);return <Panel key={key} number={`0${i+1}`} title={title} subtitle={`完整快照范围内 · 前 15 项 · ${mode==='full'?'全计数':'分数计数'}`} action={<Export filename={`${key}-${taxonomy}-${mode}.csv`} rows={rows.map(r=>({id:r.id,name:r.name,count:r.count,taxonomy,counting:mode}))}/>}><div className="people-layout"><HorizontalBars data={rows} color={color} height={530}/><div className="people-note"><span className="section-number">COVERAGE</span><strong>{fmt(stat.known_papers)}</strong><p>有该维度信息的论文</p><div className="divider"/><p>在当前 {fmt(stat.scope_papers)} 篇范围内，识别到 {fmt(stat.unique_entities)} 个不同{key==='authors'?'作者键':'机构键'}。</p><Note observation={rows.length?`首位名称关联数为 ${fmt(rows[0].count)}。这里只展示前列，不能据此推断整个分布形状。`:'暂无匹配数据。'} interpretation={mode==='full'?'每篇论文对每个关联对象贡献 1，多人合作会产生多个关联计数。':'每篇论文在该维度的 k 个不同对象之间各分配 1/k；它调整合作规模，但没有按对象总发文量标准化。'}/></div></div></Panel>})}</>}
function Sources({d}){const q=d.meta.quality,a=d.audit,b=d.source_background,v=d.cross_validation;return <><Panel number="01" title="我们到底在统计什么？" subtitle="分析单位、数据覆盖与数据源标签必须分开。"><p className="lead-text">本站分析对象是 Retraction Watch 文件中被归类为 <code>Retraction</code> 的记录，经原论文标识去重后得到的 <strong>{fmt(d.summary.paper_count)} 篇原论文</strong>。这不是全球真实撤稿论文总数，也不是 OpenAlex 所有撤稿标记记录的总量。</p><div className="source-cards"><article><Database/><h3>Retraction Watch / Crossref</h3><p>提供原论文、撤稿通知、撤稿日期与原始署名。主分析总体来自此数据集。</p><a href="https://www.crossref.org/documentation/retrieve-metadata/retraction-watch/" target="_blank" rel="noreferrer">官方数据字典 <ArrowUpRight size={14}/></a></article><article><Layers3/><h3>OpenAlex</h3><p>仅作交叉验证进度记录：已查询 {fmt(v.attempted_dois)} 个 DOI，匹配 {fmt(v.matched_papers)} 篇。DOI 匹配不等于已核实撤稿状态；这些结果不参与任何统计图表、学科分类或机构作者排序。</p><a href="https://help.openalex.org/data/works/attributes/" target="_blank" rel="noreferrer">字段说明 <ArrowUpRight size={14}/></a></article></div><div className="notice">当前 OpenAlex 匹配选择：{d.meta.openalex.selection==='all DOI'?'所有可用 DOI':'DOI 字典序前缀，是调试子集而非代表性样本'}。当前有限匹配不足以支持总体分析；全量、逐条的原论文／通知与状态核验尚未完成。</div></Panel>
 {b&&<Panel number="BACKGROUND" title="Retraction Watch 是什么团队的项目？" subtitle={`背景资料核对日期 ${b.reviewed_at}`}><p className="lead-text">创办于 {b.founded} 年。{b.description}</p><div className="source-cards">{b.founders.map(f=><article key={f.name}><h3>{f.name}</h3><p>{f.background}</p></article>)}</div><h3>{b.organization}</h3><p>{b.organization_type}。{b.database_relationship}</p><p><strong>如何收集：</strong>{b.collection}</p><p><strong>覆盖边界：</strong>{b.limitations}</p><div className="source-links">{b.sources.map(x=><a key={x.url} href={x.url} target="_blank" rel="noreferrer">{x.title} ↗</a>)}</div></Panel>}
 <Panel number="TAXONOMY" title="一级与二级学科如何划分？" subtitle="沿用 RW 官方 Subject 体系，不使用 OpenAlex 模型学科。"><p>一级由标签前缀确定，二级为前缀下的具体 Subject。例如 <code>(HSC) Medicine - Cardiology</code> 对应「健康科学 → Medicine - Cardiology」。名称中的连字符不再拆分为第三层；不同前缀下的同名标签分别保留。</p><ChartTable rows={d.taxonomies.rw.domains.map(f=>({prefix:f.id,name:f.name,english:f.english_name,children:d.taxonomies.rw.disciplines.filter(x=>x.parent_id===f.id).length,count:f.count}))} headers={[["prefix","前缀"],["name","一级学科"],["english","官方英文名"],["children","二级标签数"],["count","去重原论文数"]]}/><p>当前未分类论文：{fmt(d.taxonomies.rw.unclassified_papers)} 篇。缺失或无法识别的前缀归入「未分类」，原标签仍保留。</p><p>每篇论文在同一一级学科只计一次，因此一级数量不能由二级数量直接相加。两层分别按各自不同标签数分配 1/k 权重，二级分数计数之和也不一定等于其一级分数计数。时滞和同比始终基于未加权论文数。</p><a href={d.taxonomies.rw.hierarchy_source} target="_blank" rel="noreferrer">RW 官方分类与标签说明 ↗</a></Panel>

 {a&&<Panel number="02" title="为什么 OpenAlex 数量更大？" subtitle={`独立核查日期 ${a.checked_at} · 这些数值不参与本站统计图表计算`}><div className="table-wrap"><table><thead><tr><th>口径</th><th>数量</th><th>解释</th></tr></thead><tbody>{[['OpenAlex core：撤稿标记',a.core_flagged,'标记记录数，包含通知'],['其中 type:retraction',a.core_retraction_type,'撤稿通知类型'],['排除该类型后',a.core_without_retraction_type,'仍可能混有归为 article 的通知'],['OpenAlex corpus=all',a.all_flagged,'包含 expansion，不是已验证原论文数']].map(([n,c,t])=><tr key={n}><td>{n}</td><td>{fmt(c)}</td><td>{t}</td></tr>)}</tbody></table></div><p>一个已核查的例子：原论文 DOI <code>{a.example.original_doi}</code>，通知 DOI <code>{a.example.notice_doi}</code>。后者在 OpenAlex 中属于 article，因此只排除 retraction 类型不足以完成去重。</p><a href={a.example.crossref_source} target="_blank" rel="noreferrer">查看通知与原论文的 Crossref 关联 ↗</a><p className="caption">全量跨源核验尚未完成。不能把 OpenAlex 候选数直接替换为“全球撤稿总数”。</p></Panel>}
 <Panel number="03" title="从记录到统计" subtitle="所有统计在数据处理阶段计算；浏览器只展示预聚合结果。"><div className="method-steps">{[['01','筛选通知类别','仅纳入 Retraction；更正、关注声明、恢复发表和未知类型单列。'],['02','识别原论文','标准化原论文 DOI，次选 PMID，最后使用 RW Record ID。通知 DOI 不作为原论文键。'],['03','处理日期与重复','同文多条记录合并，取最早有效日期。负时滞和缺失日期不参与时滞统计。'],['04','聚合并发布','计算年度数量、维度分布、分位数与同比。发布统计结果及最多 36 条展示样本。']].map(([n,t,b])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{b}</p></article>)}</div><div className="table-wrap"><table><thead><tr><th>指标</th><th>定义</th><th>解释边界</th></tr></thead><tbody>{[['全计数','每篇论文对每个不同成员贡献 1','跨学科、机构、作者合计可能大于总论文数'],['分数计数','一篇论文在某维度有 k 个成员，各贡献 1/k','不是按全部发文量标准化的撤稿率'],['撤稿时滞','撤稿日期 − 原论文发表日期；年 = 天 ÷ 365.25','只描述已撤稿论文，不能估计全部论文的撤稿风险'],['分位数','对有效时间差排序，线性插值得到 P25 / P50 / P75','未加权，不随分数计数改变'],['数量同比','(本期 − 基期) ÷ 基期 × 100%','只比较两个完整年度，基期零为缺失值'],['图表分析','从聚合数据生成观察句，另外标注解释限制','不是因果分析，也不是模型对个人或机构的责任判断']].map(row=><tr key={row[0]}>{row.map(c=><td key={c}>{c}</td>)}</tr>)}</tbody></table></div></Panel>
 <Panel number="04" title="质量审计与可复现性" subtitle={`统计截止日期 ${d.meta.as_of}；生成时间 ${d.meta.generated_at}`}><div className="quality-grid">{[['源记录行',q.source_rows],['Retraction 通知行',d.meta.notice_count],['同文合并行',q.duplicate_paper_rows||0],['原论文 DOI 缺失',q.missing_doi_papers||0],['发表日期缺失',d.summary.missing_publication_date],['撤稿日期缺失',q.missing_retraction_date_papers||0],['负时滞排除',q.negative_lag_papers||0],['更正类别排除',q.excluded_correction||0],['关注声明排除',q['excluded_expression of concern']||0]].map(([n,v])=><div key={n}><span>{n}</span><b>{fmt(v)}</b></div>)}</div><p>原始文件 SHA-256：<code className="hash">{d.meta.raw_sha256}</code></p><p className="caption">截止日期不是对历史数据库版本的回放。来源可能回补、纠错或更新状态。缺少 DOI 时的不同记录仍可能指向同一论文；身份键去重不能保证跨版本完全去重。</p><p className="caption">若要估计学科撤稿率，需要相同发表年、学科、作品类型与语料范围的全部论文分母。若做生存分析，还需要加入未撤稿论文及其观察截止日期。当前页面没有声称完成这些推断。</p><a href="https://github.com/ider-zh/Scholarly-Retraction-Observatory/blob/main/docs/RESEARCH.md" target="_blank" rel="noreferrer">阅读完整研究方案与代码 ↗</a></Panel></>}
function Samples(){const {data,error}=useJSON(`${import.meta.env.BASE_URL}data/samples.json`),[search,setSearch]=useState('');if(error)return <div className="notice">{error}</div>;if(!data)return <div className="loading">加载少量展示样本…</div>;const rows=data.items.filter(p=>`${p.title} ${p.doi||''}`.toLowerCase().includes(search.toLowerCase()));return <Panel number="01" title="看见统计背后的论文" subtitle={`${data.source_papers.toLocaleString()} 篇队列中，按论文 ID 哈希排序选出的 ${data.sample_count} 条固定展示样本。`}><div className="notice">这些样本仅用于理解数据字段，不用于生成图表，也不作为代表性样本进行推断。此处搜索只覆盖这 {data.sample_count} 条样本。</div><label className="search"><Search size={18}/><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="在展示样本中搜索标题或 DOI"/></label><div className="sample-list">{rows.map(p=><article key={p.id}><div><span className="sample-tag">RW {p.rw_ids.join(' / ')}</span><h3>{p.doi?<a href={`https://doi.org/${p.doi}`} target="_blank" rel="noreferrer">{p.title}<ArrowUpRight size={15}/></a>:p.title}</h3><p>{p.subjects.map(name).join(' · ')}</p></div><dl><div><dt>发表</dt><dd>{p.published||'未知'}</dd></div><div><dt>撤稿</dt><dd>{p.retracted||'未知'}</dd></div><div><dt>时滞</dt><dd>{years(p.lag_days)} 年</dd></div></dl></article>)}</div>{!rows.length&&<p className="empty">展示样本中没有匹配结果。</p>}</Panel>}
export default function App(){const {data,error}=useJSON(`${import.meta.env.BASE_URL}data/report.json`);const [tab,setTab]=useState('overview'),[mobile,setMobile]=useState(false);const current=NAV.find(v=>v[0]===tab);return <div className="app"><aside className={mobile?'sidebar open':'sidebar'}><a className="brand" href="#" onClick={e=>{e.preventDefault();setTab('overview')}}><span className="brand-mark">R<span>·</span></span><div>撤稿研究观测站<small>SCHOLARLY RETRACTIONS</small></div></a><div className="nav-label">研究导航</div><nav>{NAV.map(([key,label,Icon])=><button key={key} className={tab===key?'selected':''} onClick={()=>{setTab(key);setMobile(false);window.scrollTo({top:0})}}><Icon size={19}/>{label}{tab===key&&<span className="nav-dot"/>}</button>)}</nav><div className="sidebar-bottom"><span className="small-label">RESEARCH SNAPSHOT</span><strong>{data?.meta.as_of||'载入中'}</strong><p>描述可验证的现象，<br/>保留解释的边界。</p><a href="https://github.com/ider-zh/Scholarly-Retraction-Observatory" target="_blank" rel="noreferrer">研究代码 <ArrowUpRight size={15}/></a></div></aside>{mobile&&<button aria-label="关闭导航" className="backdrop" onClick={()=>setMobile(false)}/>}
 <div className="workspace"><header className="topbar"><button className="menu-button" aria-label="切换导航" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button><span>研究 / <b>{current[1]}</b></span><a href="https://www.crossref.org/documentation/retrieve-metadata/retraction-watch/" target="_blank" rel="noreferrer">Retraction Watch / Crossref <ArrowUpRight size={14}/></a></header><main><div className="page-heading"><div><span className="eyebrow">SCHOLARLY RETRACTION OBSERVATORY</span><h1>{current[1]}</h1><p>{tab==='overview'?'用时间、学科与研究共同体的视角，观察撤稿记录。':tab==='disciplines'?'比较学科分布、年度变化与发表到撤稿的时间。':tab==='people'?'观察完整 RW 队列的机构与作者署名关联。':tab==='sources'?'清楚说明数据来自哪里、统计了什么，以及不能推断什么。':'少量真实记录，帮助理解统计单位和日期字段。'}</p></div><div className="snapshot-label"><Clock3 size={16}/><span>统计快照<b>{data?.meta.as_of||'—'}</b></span></div></div>
 {error?<div className="notice error" role="alert">{error}。请刷新页面重试，或确认已发布统计快照。</div>:!data?<div className="loading" role="status">正在加载统计快照…</div>:tab==='overview'?<Overview d={data}/>:tab==='disciplines'?<Disciplines d={data}/>:tab==='people'?<People d={data}/>:tab==='sources'?<Sources d={data}/>:<Samples/>}
 <footer><span>统计来源：Retraction Watch / Crossref · CC0 数据</span><span>撤稿关联不等于个人或机构存在不当行为</span></footer></main></div></div>}
